<?php

/**
 * Implements hook_filter_info().
 */
function wysiwyg_callouts_filter_info() {
  $filters['wysiwyg_callout'] = array(
    'title' => t('Convert Callout tags to markup'),
    'description' => t('This filter will convert [[{type:wysiwyg_callout... ]] tags into markup.'),
    'process callback' => 'wysiwyg_callout_filter',
    'weight' => 2,
  );
  
  return $filters;
}

/**
 * Filter process callback.
 *
 * @param $text
 * @param null $filter
 * @param null $format
 * @param null $langcode
 * @param null $cache
 * @param null $cache_id
 *
 * @return mixed
 */
function wysiwyg_callout_filter($text, $filter = NULL, $format = NULL, $langcode = NULL, $cache = NULL, $cache_id = NULL) {
  $build = array(
    '#theme' =>'wysiwyg_callout',
  );
  $new_text =  str_replace('##WYSIWYG_CALLOUT##', drupal_render($build), $text);
  return $new_text;
}

/**
 * Implements hook_theme().
 *
 * @return array
 */
function wysiwyg_callouts_theme() {
  return array(
    'wysiwyg_callout' => array(
      'template' => 'theme/wysiwyg-callout',
    ),
  );
}

/**
 * Implements hook_page_alter().
 *
 * Filter process callbacks get cached in a manner which prevents
 * the dynamic adding to CSS/JS stylesheets. For now, our styles are
 * compact enough that including them on all pages isn't that bad.
 *
 * @todo: refactor this out.
 *
 * @param $page
 */
function wysiwyg_callouts_page_alter(&$page) {
  $page['header']['#attached']['css'][] = array(
    'data' => drupal_get_path('module', 'wysiwyg_callouts') . '/assets/wysiwyg_callout.css',
    'type' => 'file',
  );
}